// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        //return ios;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB014RCpDL9g_NwcZwDuOp_dj1DtJWX1Nc',
    appId: '1:801540560335:web:2385ee45e11c13e8186eba',
    messagingSenderId: '801540560335',
    projectId: 'fixlock-app',
    authDomain: 'fixlock-app.firebaseapp.com',
    storageBucket: 'fixlock-app.appspot.com',
    measurementId: 'G-GPQF0VG8Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDeE_3FF3boA57PsvlJHlMbo9SlNgPSmI',
    appId: '1:801540560335:android:644208ed30437918186eba',
    messagingSenderId: '801540560335',
    projectId: 'fixlock-app',
    storageBucket: 'fixlock-app.appspot.com',
  );

  /*static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLstgVe3E-UF3Iv2gQHeQZnnsx5dPFxU',
    appId: '1:813395912100:ios:4abdf2c31f22aa5456cd31',
    messagingSenderId: '813395912100',
    projectId: 'smart-medication-app',
    storageBucket: 'smart-medication-app.appspot.com',
    iosClientId: '504805874781-65229c0qcb87fa1sflq6bk08vp2336kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medwell',
  );*/
}
